Patient.create(name: 'Cierra Vega')
Patient.create(name: 'Alden Cantrell')
Patient.create(name: 'Kierra Gentry')
Patient.create(name: 'Pierre Cox')
Patient.create(name: 'Thomas Crane')
Patient.create(name: 'Miranda Shaffer')
Patient.create(name: 'Bradyn Kramer')
Patient.create(name: 'Alvaro Mcgee')
